twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        distance_unit: 'km'
        elevation_unit: 'm'
        duration_unit: 'min'
        plan_duration_unit: 'weeks'
when@test:
    twig:
        strict_variables: true
