version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "15432:5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [ "1025", "1080" ]
###< symfony/mailer ###

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
